
CREATE DATABASE IF NOT EXISTS dear_diary;

USE dear_diary;

DROP TABLE IF EXISTS user_info;

-- 테이블 생성
CREATE TABLE user_info(
	id					BIGINT(10)UNSIGNED		PRIMARY KEY AUTO_INCREMENT
	,member_id		VARCHAR(10)				   UNIQUE KEY NOT NULL
	,pw	 			VARCHAR(300)				NOT NULL
	,name				VARCHAR(20)					NOT NULL
	,birth	 		DATE							NOT NULL
	,affiliated_at TIMESTAMP 					NOT NULL DEFAULT CURRENT_TIMESTAMP()
	,updated_at 	TIMESTAMP 					NOT NULL DEFAULT CURRENT_TIMESTAMP()
	,deleted_at 	TIMESTAMP					 
);
